name: commander_deck
description: A Flutter app for daily Commander card suggestions from Scryfall API
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  intl: ^0.19.0
  url_launcher: ^6.1.14
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Configuration for flutter_launcher_icons§

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/commander_deck.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/commander_deck.png"